# Граници по зони (по подразбиране). Можеш да ги сменяш от "Настройки".
defaults:
  HRmax: 190
  CS_run_kmh: 18.0   # Critical Speed (бягане) в km/h
  CP_bike_w: 260     # Critical Power (колело) в W

zones:
  hr:          # % от HRmax
    Z1: [0.60, 0.75]
    Z2: [0.76, 0.80]
    Z3: [0.81, 0.88]
    Z4: [0.89, 0.95]
    Z5: [0.96, 1.00]
  pct_cs:      # % от CS за бягане
    Z1: [0.60, 0.75]
    Z2: [0.76, 0.80]
    Z3: [0.81, 0.88]
    Z4: [0.89, 0.95]
    Z5: [0.96, 1.10]
  pct_cp:      # % от CP за колоездене
    Z1: [0.55, 0.75]
    Z2: [0.76, 0.85]
    Z3: [0.86, 0.95]
    Z4: [0.96, 1.05]
    Z5: [1.06, 1.20]

generator:
  weekly_minutes_target: 450   # общ целеви обем за седмица (мин)
  distribution_pct:            # разпределение по зони по подразбиране
    Z1: 0.45
    Z2: 0.25
    Z3: 0.15
    Z4: 0.08
    Z5: 0.02
  acwr_high: 1.5               # праг за висок риск
  acwr_reduce_volume_pct: 0.20 # -20% обем
