name: Sync Strava

on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"   # всеки час и 5-тата минута

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run sync
        env:
          DB_URL: ${{ secrets.DB_URL }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          # Optional defaults
          HRMAX_DEFAULT: "190"
          CS_RUN_KMH_DEFAULT: "18.0"
          CP_BIKE_W_DEFAULT: "260.0"
        run: python sync.py
